# Generated by Django 3.0.6 on 2020-06-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pseudo_shape',
            field=models.CharField(choices=[('AS', 'Asscher'), ('CU', 'Cushion'), ('EC', 'Emerald'), ('HS', 'Heart'), ('MQ', 'Marquise'), ('OV', 'Oval'), ('PR', 'Princess'), ('PS', 'Pear Shape'), ('RA', 'Radiant'), ('RD', 'Round')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='clarity',
            field=models.CharField(choices=[('FL', 'FL'), ('I1', 'I1'), ('I2', 'I2'), ('IF', 'IF'), ('SI', 'SI'), ('SI1', 'SI1'), ('SI2', 'SI2'), ('SI3', 'SI3'), ('VS', 'VS'), ('VS1', 'VS1'), ('VS2', 'VS2'), ('VVS1', 'VVS1'), ('VVS2', 'VVS2')], default='FL', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('', ''), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N')], default='D', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='shape',
            field=models.CharField(choices=[('OTHER', 'OTHER'), ('AS', 'Asscher'), ('CU', 'Cushion'), ('EC', 'Emerald'), ('HS', 'Heart'), ('MQ', 'Marquise'), ('OV', 'Oval'), ('PR', 'Princess'), ('PS', 'Pear Shape'), ('RA', 'Radiant'), ('RD', 'Round')], max_length=20),
        ),
    ]
