# Generated by Django 3.0.7 on 2020-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200714_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='jewellery/')),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
