# Generated by Django 3.0.6 on 2020-06-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200601_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pseudo_shape',
            field=models.CharField(choices=[('AS', 'Asscher'), ('BU', 'BU1'), ('CU', 'Cushion'), ('EC', 'Emerald'), ('EU', 'EU1'), ('HS', 'Heart'), ('MQ', 'Marquise'), ('OV', 'Oval'), ('OM', 'OM1'), ('PR', 'Princess'), ('PS', 'Pear Shape'), ('RA', 'Radiant'), ('RD', 'Round'), ('STB', 'STB1'), ('TB', 'TB1'), ('TR', 'TR1')], default='OTHER', max_length=20),
        ),
    ]
