# Generated by Django 3.0.7 on 2020-07-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_jewellery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jewellery',
            options={'verbose_name_plural': 'Jewellery'},
        ),
        migrations.AddField(
            model_name='product',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
