# Generated by Django 3.0.7 on 2020-07-05 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200620_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='fname',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='Spl@ymail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='lname',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='clarity',
            field=models.CharField(choices=[('FL', 'FL'), ('IF', 'IF'), ('VVS1', 'VVS1'), ('VVS2', 'VVS2'), ('VS1', 'VS1'), ('VS2', 'VS2'), ('SI1', 'SI1'), ('SI2', 'SI2'), ('SI3', 'SI3'), ('I1', 'I1'), ('I2', 'I2')], default='FL', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='cut',
            field=models.CharField(blank=True, choices=[('EX', 'EX'), ('VG', 'VG'), ('G', 'GD'), ('F', 'FR')], default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fl',
            field=models.CharField(blank=True, choices=[('N', 'NONE'), ('F', 'FAINT'), ('M', 'MEDIUM'), ('S', 'STRONG'), ('VS', 'VERY STRONG')], default='-', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lab',
            field=models.CharField(choices=[('GIA', 'GIA'), ('EGL USA', 'EGL USA'), ('OWN', 'Non-Certified')], default='OWN', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='pol',
            field=models.CharField(blank=True, choices=[('EX', 'EX'), ('VG', 'VG'), ('G', 'GD'), ('F', 'FR')], default='-', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pseudo_shape',
            field=models.CharField(choices=[('RD', 'Round'), ('BU', 'BU1'), ('CU', 'Cushion'), ('EC', 'Emerald'), ('EU', 'EU1'), ('HS', 'Heart'), ('MQ', 'Marquise'), ('OV', 'Oval'), ('OM', 'OM1'), ('PR', 'Princess'), ('PS', 'Pear Shape'), ('RA', 'Radiant'), ('RD', 'Round'), ('AS', 'Asscher'), ('STB', 'STB1'), ('TB', 'TB1'), ('TR', 'TR1')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='shape',
            field=models.CharField(choices=[('OTHER', 'OTHER'), ('RD', 'Round'), ('AS', 'Asscher'), ('CU', 'Cushion'), ('EC', 'Emerald'), ('HS', 'Heart'), ('MQ', 'Marquise'), ('OV', 'Oval'), ('PR', 'Princess'), ('PS', 'Pear Shape'), ('RA', 'Radiant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sym',
            field=models.CharField(blank=True, choices=[('X', 'EX'), ('VG', 'VG'), ('G', 'GD'), ('F', 'FR')], default='-', max_length=10, null=True),
        ),
    ]
